### ISSUE TITLE
Whether the original remote sensing data can be used directly as GT in Shi yujiao?

### ISSUE THREAD

**Issue by liguopeng0923** [fferflo/tiledwebmaps#1]
Whether I can select corresponding aerial images in [this paper](https://github.com/shiyujiao/HighlyAccurate) as the ground truth?
In other words, do your aerial images have some difference with [this paper](https://github.com/shiyujiao/HighlyAccurate) in your common parts?

**Comment by fferflo** [comment]
The images in the paper by Shi etal have predefined shape and pose (location, orientation, pixel resolution and size), whereas the tiledwebmaps library is used to retrieve images with arbitrary shape and pose from some tile provider, which is what we did in our paper. This allows for example arbitrary data augmentation and continuous tracking over time.

The images from [this paper](https://github.com/shiyujiao/HighlyAccurate) would have to be included in the [cvgl_data](https://github.com/fferflo/cvgl_data) library as a new dataset or be loaded manually.

**Comment by liguopeng0923** [comment]
Thanks, I have no problems.
